<?php

namespace AppBundle\Repository;

/**
 * AcceptedOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcceptedOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
