<?php

namespace AppBundle\Repository;

/**
 * AvailableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailableRepository extends \Doctrine\ORM\EntityRepository
{
}
